#pragma once

#include "GLFW/glfw3.h"

using KeyCode = uint16_t;

namespace Key {

	enum : KeyCode {

		W = GLFW_KEY_W,
		A = GLFW_KEY_A,
		S = GLFW_KEY_S,
		D = GLFW_KEY_D,
		SPACE = GLFW_KEY_SPACE,
		UP = GLFW_KEY_UP,
		LEFT = GLFW_KEY_LEFT,
		DOWN = GLFW_KEY_DOWN,
		RIGHT = GLFW_KEY_RIGHT,
		ESCAPE = GLFW_KEY_ESCAPE,
		F1 = GLFW_KEY_F1,
		BACK = GLFW_KEY_BACKSPACE,
		ENTER = GLFW_KEY_ENTER,
		LSHIFT = GLFW_KEY_LEFT_SHIFT,
		LCONTROL = GLFW_KEY_LEFT_CONTROL
	};

}